# Generated by Django 5.2.13 on 2026-09-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal del banner', max_length=150)),
                ('subtitulo', models.TextField(help_text='Descripción o detalles promocionales del banner')),
                ('badge', models.CharField(default='OFERTA TECH', help_text='Etiqueta superior (ej: EQUIPAMIENTO DE CAJA, TENDENCIA 2026)', max_length=60)),
                ('badge_gold', models.BooleanField(default=False, help_text='Marcar para mostrar la etiqueta en tono dorado/amarillo')),
                ('url_destino', models.CharField(default='/', help_text='Enlace al hacer clic en el botón (ej: /categoria/smart-pos-retail-tech/)', max_length=250)),
                ('texto_boton', models.CharField(default='Ver Colección', help_text='Texto del botón de acción', max_length=60)),
                ('estilo_fondo', models.CharField(choices=[('dark-navy', 'Dark Navy Metallic'), ('vibrant-blue', 'Azul Vibrante'), ('gradient-purple', 'Púrpura Deep'), ('emerald-green', 'Verde Esmeralda')], default='dark-navy', help_text='Estilo de gradiente de fondo', max_length=30)),
                ('icono_fontawesome', models.CharField(default='fa-cash-register', help_text='Icono FontAwesome decorativo de fondo (ej: fa-cash-register, fa-headphones, fa-print)', max_length=50)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición en la portada')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar en la portada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionales',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='autor',
            field=models.CharField(blank=True, default='Rapidassure', help_text='Nombre del autor del artículo (opcional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='codigo',
            field=models.CharField(help_text='Código en mayúsculas (ej: RAPIDA10)', max_length=50, unique=True),
        ),
    ]
