# Generated by Django 5.2.13 on 2026-09-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_bannerpromocional_alter_blogpost_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpromocional',
            name='icono_fontawesome',
            field=models.CharField(choices=[('fa-cash-register', 'Caja Registradora / Smart POS'), ('fa-headphones', 'Audífonos / Audio Profesional'), ('fa-print', 'Impresora Térmica / Insumos'), ('fa-microchip', 'Microchip / Gadgets Tech'), ('fa-truck-fast', 'Despacho Corporativo'), ('fa-shield-halved', 'Garantía / Cobertura Care+'), ('fa-bolt', 'Smart / Oferta Relámpago'), ('fa-tag', 'Etiqueta de Descuento / Oferta'), ('fa-store', 'Tienda / Comercio Retail'), ('fa-qrcode', 'Lector QR / Código de Barras'), ('fa-mobile-screen', 'POS Móvil Android'), ('fa-boxes-stacked', 'Inventario / Accesorios')], default='fa-cash-register', help_text='Icono FontAwesome decorativo de fondo', max_length=50),
        ),
    ]
