# Generated by Django 5.2.13 on 2026-09-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_alter_bannerpromocional_icono_fontawesome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='giro_comercial',
            field=models.CharField(blank=True, default='', help_text='Giro comercial de la empresa', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='razon_social',
            field=models.CharField(blank=True, default='', help_text='Razón social para la factura', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='requiere_factura',
            field=models.BooleanField(default=False, help_text='Marcar si el cliente solicitó Factura Electrónica'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rut_empresa',
            field=models.CharField(blank=True, default='', help_text='RUT de la empresa para la factura', max_length=15),
        ),
    ]
