# Generated by Django 5.2.13 on 2026-09-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_pedido_giro_comercial_pedido_razon_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('ENVIO', 'Despacho a Domicilio'), ('RETIRO', 'Retiro en Local')], default='ENVIO', help_text='Forma de entrega seleccionada por el cliente', max_length=20),
        ),
    ]
