# Generated by Django 5.2.13 on 2026-09-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpromocional',
            name='estilo_fondo',
            field=models.CharField(choices=[('dark-navy', 'Dark Navy Metallic (Azul Marino & Índigo)'), ('vibrant-blue', 'Azul Cobalto Tech (Azul Eléctrico & Royal)'), ('gradient-purple', 'Cyberpunk Violet (Púrpura & Violeta Profundo)'), ('emerald-green', 'Cyber Emerald (Verde Esmeralda Tech)'), ('neon-cyan', 'Neón Cyan & Deep Sea (Turquesa & Cyan Brillante)'), ('crimson-red', 'Crimson Gamer (Rojo Rubí & Carmesí Tech)'), ('sunset-amber', 'Ámbar Gold & Sunset (Dorado Ámbar & Cobre)'), ('titanium-carbon', 'Titanio & Carbón (Negro Grafito & Pizarra)'), ('electric-violet', 'Violeta Neón & Magenta (Fucsia Cyber & Púrpura)'), ('matrix-tech', 'Matrix Tech (Verde Neón Terminal)'), ('midnight-aurora', 'Aurora Boreal (Azul Medianoche & Teal)'), ('solar-flare', 'Solar Flare (Naranja Fuego & Bronce Tech)')], default='dark-navy', help_text='Estilo de gradiente de fondo', max_length=30),
        ),
        migrations.AlterField(
            model_name='bannerpromocional',
            name='icono_fontawesome',
            field=models.CharField(choices=[('fa-cash-register', 'Caja Registradora / Smart POS'), ('fa-mobile-screen', 'POS Móvil Android / Terminal Portátil'), ('fa-barcode', 'Lector de Código de Barras'), ('fa-qrcode', 'Código QR / Pago Digital'), ('fa-print', 'Impresora Térmica / Recibos y Tickets'), ('fa-receipt', 'Boleta / Facturación Electrónica'), ('fa-credit-card', 'Tarjeta de Crédito / Terminal Transbank'), ('fa-store', 'Tienda / Comercio Retail'), ('fa-laptop', 'Laptop / Computador Portátil'), ('fa-desktop', 'PC Escritorio / All-in-One'), ('fa-server', 'Servidores / Cloud Data Center'), ('fa-tv', 'Smart TV / Monitores & Pantallas'), ('fa-tablet-screen-button', 'Tablet / Pantalla Táctil'), ('fa-mobile-screen-button', 'Smartphone / Telefonía Móvil'), ('fa-headphones', 'Audífonos / Audio Profesional'), ('fa-volume-high', 'Parlantes Bluetooth / Sonido'), ('fa-sliders', 'Mezclador / Consola de Audio'), ('fa-microphone', 'Micrófono / Streaming Tech'), ('fa-gamepad', 'Gaming / Consolas & Joysticks'), ('fa-vr-cardboard', 'Realidad Virtual / Visores VR'), ('fa-wifi', 'WiFi / Router & Conectividad'), ('fa-network-wired', 'Red Cableada / Ethernet & Switches'), ('fa-satellite-dish', 'Telecomunicaciones / Antenas'), ('fa-cloud-arrow-up', 'Nube / Copia de Seguridad & Cloud'), ('fa-microchip', 'Microchip / Procesadores & Hardware'), ('fa-hard-drive', 'Disco SSD / Almacenamiento de Datos'), ('fa-keyboard', 'Teclados & Mouse Periféricos'), ('fa-battery-full', 'Baterías / Powerbanks & Autonomía'), ('fa-plug', 'Cargadores / Enchufes & Cables Tech'), ('fa-boxes-stacked', 'Inventario / Accesorios Tech'), ('fa-video', 'Cámaras de Seguridad & CCTV'), ('fa-camera', 'Cámaras Fotográficas / Lentes'), ('fa-shield-halved', 'Garantía / Cobertura Rapidassure Care+'), ('fa-shield-check', 'Ciberseguridad / Protección Digital'), ('fa-fingerprint', 'Biometría / Control de Acceso'), ('fa-robot', 'Robótica & Inteligencia Artificial'), ('fa-screwdriver-wrench', 'Servicio Técnico & Reparación'), ('fa-bolt', 'Oferta Relámpago / Flash Tech'), ('fa-fire', 'Hot Tech / Lo Más Vendido'), ('fa-tag', 'Etiqueta de Descuento / Promo'), ('fa-percent', 'Porcentaje Descuento / Cyber Sale'), ('fa-gem', 'Edición Premium / Gama Alta'), ('fa-truck-fast', 'Despacho Express / Envío Rápido')], default='fa-cash-register', help_text='Icono FontAwesome decorativo de fondo', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especie_dato_curioso',
            field=models.TextField(blank=True, help_text='Ficha técnica o características destacadas del equipo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especie_estado_conservacion',
            field=models.CharField(blank=True, help_text='Ej: Garantía 24 Meses, Norma IP65', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especie_habitat',
            field=models.CharField(blank=True, help_text='Ej: Retail, Supermercados, Bodegas y Logística', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especie_nombre_cientifico',
            field=models.CharField(blank=True, help_text='Ej: SKU-TEC-900-V2', max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especie_nombre_comun',
            field=models.CharField(blank=True, help_text="Ej: Terminal POS Táctil 15'', Lector Láser 2D", max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tiene_ficha_especie',
            field=models.BooleanField(default=True, help_text='Marcar para incluir Especificación Técnica Extendida'),
        ),
    ]
