# Generated by Django 5.2.13 on 2026-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_alter_bannerpromocional_estilo_fondo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, help_text='Marcar para activar precio de oferta promocional'),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento (ej: 15 para 15% OFF)'),
        ),
    ]
