# Generated by Django 5.2.13 on 2026-09-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0025_producto_en_oferta_producto_porcentaje_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_autorizacion',
            field=models.CharField(blank=True, help_text='Código de autorización Transbank Webpay', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cuotas',
            field=models.IntegerField(default=0, help_text='Cantidad de cuotas si aplica'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='WEBPAY', help_text='Pasarela de pago utilizada', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tarjeta_ultimos_digitos',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(blank=True, help_text='Tipo de pago Webpay (Débito, Crédito, etc.)', max_length=50, null=True),
        ),
    ]
