# Generated by Django 5.2.13 on 2026-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_pedido_codigo_autorizacion_pedido_cuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', help_text='Marca o fabricante del producto (ej: Zebra, Epson, Honeywell, SAT)', max_length=100, verbose_name='Marca'),
        ),
    ]
