# Generated by Django 5.2.13 on 2026-09-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0027_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura del paquete en cm para cálculo de envío Blue Express', max_digits=6, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho del paquete en cm para cálculo de envío Blue Express', max_digits=6, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largo del paquete en cm para cálculo de envío Blue Express', max_digits=6, null=True, verbose_name='Largo (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso físico del paquete en kilogramos (ej: 0.50 para 500g)', max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
    ]
