# Generated by Django 5.2.13 on 2026-09-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_producto_alto_producto_ancho_producto_largo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(blank=True, default='Santiago', help_text='Comuna de entrega', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.IntegerField(default=0, help_text='Costo cobrado por despacho Blue Express'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='region',
            field=models.CharField(blank=True, default='Metropolitana de Santiago', help_text='Región de entrega', max_length=120),
        ),
    ]
