# Generated by Django 5.2.13 on 2026-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_pedido_comuna_pedido_costo_envio_pedido_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='punto_entrega_id',
            field=models.CharField(blank=True, default='', help_text='ID Agencia Blue Express', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='punto_entrega_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre de Agencia Blue Express', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('ENVIO', 'Despacho a Domicilio'), ('RETIRO', 'Retiro en Local'), ('PUNTO_BLUE', 'Punto Blue Express (Pick-up / Copec)')], default='ENVIO', help_text='Forma de entrega seleccionada por el cliente', max_length=20),
        ),
    ]
