# Generated by Django 5.2.13 on 2026-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0030_pedido_punto_entrega_id_pedido_punto_entrega_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('ENVIO', 'Despacho a Domicilio'), ('RETIRO', 'Retiro en Local'), ('PUNTO_BLUE', 'Punto Blue Express (Pick-up / Copec)'), ('GRATIS_RM', 'Envío Gratis RM (+ $19.990)')], default='ENVIO', help_text='Forma de entrega seleccionada por el cliente', max_length=20),
        ),
    ]
