# Generated by Django 5.2.13 on 2026-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0031_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.PositiveIntegerField(blank=True, help_text='Precio final de oferta en pesos CLP', null=True, verbose_name='Precio de Oferta ($ CLP)'),
        ),
        migrations.AlterField(
            model_name='logpedido',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Pedido Creado'), ('PAGO_OK', 'Pago Confirmado'), ('ESTADO_CAMBIO', 'Cambio de Estado'), ('SEGUIMIENTO', 'Datos de Seguimiento'), ('ERROR', 'Error / Fallo de Pago'), ('CANCELADO', 'Pedido Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logproducto',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('TOGGLE', 'Cambio de Estado'), ('VENTA', 'Venta Realizada'), ('ELIMINACION', 'Eliminación')], max_length=20),
        ),
    ]
