# Generated by Django 5.2.13 on 2026-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0032_producto_precio_oferta_alter_logpedido_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='excluir_ofertas',
            field=models.BooleanField(default=False, help_text='No aplicar descuento sobre productos que ya tienen rebaja u oferta promocional.', verbose_name='Excluir productos en oferta'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='monto_minimo_compra',
            field=models.PositiveIntegerField(default=0, help_text='Monto mínimo de compra en CLP para que aplique el cupón. 0 para sin mínimo.', verbose_name='Monto Mínimo de Compra ($ CLP)'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='tope_descuento',
            field=models.PositiveIntegerField(blank=True, help_text='Monto máximo de descuento permitido en CLP. Dejar en blanco para sin tope.', null=True, verbose_name='Tope de Descuento ($ CLP)'),
        ),
    ]
